name: deploy mkdocs

on:
  push:
    branches:
      - master
      - main

jobs:
  docs:
    uses: kube-the-home/github-actions/.github/workflows/mkdocs.yaml@e698429ae3d6096c14d7eb6d2ffef1da8c26cdea # v1.4.1
    permissions:
      contents: write
