name: deploy mkdocs

on:
  push:
    branches:
      - master
      - main

jobs:
  docs:
    uses: kube-the-home/github-actions/.github/workflows/mkdocs.yaml@cc715d5c26c3498c970eb730b01344aa61c5152d # v1.3.4
    permissions:
      contents: write
