name: deploy mkdocs

on:
  push:
    branches:
      - master
      - main

jobs:
  docs:
    uses: kube-the-home/github-actions/.github/workflows/mkdocs.yaml@b67640d904b560a3a20f5cb94e6ddd5bfa955d65 # v1.4.10
    permissions:
      contents: write
